name: PugFreedomMod
main: me.totalfreedom.totalfreedommod.TotalFreedomMod
version: ${tfm.build.version}
description: Plugin for the Pug Freedom server.
depend: [Aero, WorldEdit]
softdepend: [BukkitTelnet, Essentials]
authors: [Madgeek1450, Prozza, Phoenix]

# plugin.yml is no longer used to define commands.
